import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CHAT_THEMES, setChatThemeSettings } from '../services/chatTheme';
export default function ChatThemeSettings({value,onChange,onBack,required=false}){
 const select=async id=>onChange?.(await setChatThemeSettings({id}));
 return <SafeAreaView style={styles.page}><View style={styles.header}>{!required?<Pressable onPress={onBack}><Text style={styles.back}>‹ Back</Text></Pressable>:<View style={styles.spacer}/>}<Text style={styles.title}>{required?'Choose Theme':'App Theme'}</Text><View style={styles.spacer}/></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.help}>{required?'Choose a theme to continue. Modern Blue is the default recommendation.':'Theme selection is kept in Settings. Only approved palette colors are used.'}</Text>{Object.values(CHAT_THEMES).map(theme=><Pressable key={theme.id} style={[styles.card,value?.id===theme.id&&styles.selected]} onPress={()=>select(theme.id)}><View style={styles.swatches}>{Object.values(theme.colors).filter((v,i,a)=>a.indexOf(v)===i).slice(0,5).map(color=><View key={color} style={[styles.dot,{backgroundColor:color}]}/>)}</View><Text style={styles.label}>{theme.label}{theme.id==='modern-blue'?' (Default)':''}</Text></Pressable>)}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#0F172A'},header:{minHeight:62,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#2563EB'},back:{color:'#E0E7FF',fontWeight:'800',width:64},spacer:{width:64},title:{color:'#E0E7FF',fontSize:18,fontWeight:'800'},content:{padding:18,gap:12},help:{color:'#E0E7FF',lineHeight:20,marginBottom:4},card:{padding:16,borderRadius:14,borderWidth:1,borderColor:'#3B82F6',backgroundColor:'#0F172A'},selected:{borderWidth:3,borderColor:'#10B981'},swatches:{flexDirection:'row',gap:8,marginBottom:10},dot:{width:32,height:32,borderRadius:16},label:{color:'#E0E7FF',fontSize:15,fontWeight:'800'}});
