import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { platformApi } from '../services/platform';

export default function ForwardMessageModal({ visible, message, onClose }) {
  const [chats, setChats] = useState([]); const [selected, setSelected] = useState([]); const [query, setQuery] = useState('');
  const [retryToken, setRetryToken] = useState(0);
  const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => {
    if (!visible) return;
    let active = true; setLoading(true); setError(''); setSelected([]); setQuery('');
    Promise.all([platformApi.listChats('private'), platformApi.listChats('group')]).then(([privateResult, groupResult]) => {
      if (!active) return;
      const privateChats = (privateResult.data?.chats || []).map(chat => ({ ...chat, id: Number(chat.id), kind: 'Contact' }));
      const groups = (groupResult.data?.chats || []).map(chat => ({ ...chat, id: Number(chat.id), kind: 'Group' }));
      const seen = new Set(); setChats([...privateChats, ...groups].filter(chat => chat.id > 0 && !seen.has(chat.id) && seen.add(chat.id)));
    }).catch(e => { if (active) setError(e.message || 'Unable to load contacts and groups.'); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [visible, retryToken]);
  const filtered = useMemo(() => { const term = query.trim().toLowerCase(); return term ? chats.filter(chat => `${chat.name || ''} ${chat.user_id || ''} ${chat.kind || ''}`.toLowerCase().includes(term)) : chats; }, [chats, query]);
  const toggle = chat => setSelected(current => current.some(item => item.id === chat.id) ? current.filter(item => item.id !== chat.id) : [...current, chat]);
  const forward = async () => { if (!message?.id || !selected.length || busy) return; setBusy(true); setError(''); try { const result = await platformApi.forwardMessage(Number(message.id), selected.map(chat => Number(chat.id))); if (!Number(result?.data?.forwarded || 0)) throw new Error('The server did not confirm that the message was forwarded.'); onClose?.(); } catch (e) { const detail = e?.details?.message || e?.details?.error || e?.message || 'Unable to forward message.'; setError(detail); Alert.alert('Forward failed', detail); } finally { setBusy(false); } };
  return <Modal visible={Boolean(visible)} animationType="slide" onRequestClose={onClose}><View style={styles.page}>
    <View style={styles.header}><Pressable disabled={busy} onPress={onClose}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.title}>Forward message</Text><View style={styles.spacer} /></View>
    <View style={styles.preview}><Text style={styles.previewLabel}>Message</Text><Text numberOfLines={3} style={styles.previewText}>{message?.body || ''}</Text></View>
    {selected.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{selected.map(chat => <View key={chat.id} style={styles.chip}><Text style={styles.chipText}>{chat.name || 'Chat'}</Text></View>)}</ScrollView> : null}
    <TextInput style={styles.search} value={query} onChangeText={setQuery} placeholder="Search contacts or chats" placeholderTextColor="#7f8aa3" autoCapitalize="none" />
    {error ? <View style={styles.errorCard}><Text style={styles.error}>{error}</Text><Pressable onPress={() => setRetryToken(value => value + 1)}><Text style={styles.retry}>Try again</Text></Pressable></View> : null}
    {loading ? <View style={styles.loading}><ActivityIndicator color="#3157d5" /><Text style={styles.muted}>Loading contacts and groups…</Text></View> : <ScrollView contentContainerStyle={styles.list}>{filtered.map(chat => { const checked = selected.some(item => item.id === chat.id); return <Pressable key={`${chat.kind}-${chat.id}`} style={styles.row} onPress={() => toggle(chat)} disabled={busy}><View style={[styles.check, checked && styles.checkActive]}>{checked ? <Text style={styles.checkText}>✓</Text> : null}</View><View style={styles.meta}><Text numberOfLines={1} style={styles.name}>{chat.name || 'Conversation'}</Text><Text style={styles.kind}>{chat.kind}</Text></View></Pressable>; })}{!filtered.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>No chats found</Text><Text style={styles.muted}>Try a different contact or group name.</Text></View> : null}</ScrollView>}
    <View style={styles.footer}><Text style={styles.selectedCount}>{selected.length ? `${selected.length} selected` : 'Select one or more recipients'}</Text><Pressable style={[styles.forwardButton, (!selected.length || busy) && styles.disabled]} disabled={!selected.length || busy} onPress={forward}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.forwardText}>Forward</Text>}</Pressable></View>
  </View></Modal>;
}
const styles = StyleSheet.create({page:{flex:1,backgroundColor:'#f5f7fb',paddingTop:28},header:{minHeight:62,flexDirection:'row',alignItems:'center',paddingHorizontal:14,backgroundColor:'#3157d5'},back:{color:'#fff',fontWeight:'800',width:54},title:{flex:1,textAlign:'center',color:'#fff',fontSize:18,fontWeight:'800'},spacer:{width:54},preview:{margin:14,padding:14,borderRadius:14,backgroundColor:'#fff',borderWidth:1,borderColor:'#e2e7f0'},previewLabel:{color:'#3157d5',fontSize:11,fontWeight:'800'},previewText:{marginTop:5,color:'#172033',fontSize:14,lineHeight:20},chips:{paddingHorizontal:14,paddingBottom:6,gap:7},chip:{paddingHorizontal:10,paddingVertical:7,borderRadius:16,backgroundColor:'#eef2ff'},chipText:{color:'#3157d5',fontSize:11,fontWeight:'800'},search:{marginHorizontal:14,minHeight:48,paddingHorizontal:14,borderWidth:1,borderColor:'#d8deea',borderRadius:12,color:'#172033',backgroundColor:'#fff'},errorCard:{margin:14,padding:10,borderRadius:10,backgroundColor:'#fee2e2'},error:{color:'#b91c1c'},retry:{marginTop:6,color:'#3157d5',fontWeight:'800'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:8},muted:{color:'#68748a',fontSize:12},list:{padding:14,paddingBottom:110},row:{minHeight:64,flexDirection:'row',alignItems:'center',paddingHorizontal:10,borderBottomWidth:1,borderBottomColor:'#edf0f5',backgroundColor:'#fff'},check:{width:24,height:24,borderRadius:12,borderWidth:1.5,borderColor:'#cbd5e1',alignItems:'center',justifyContent:'center'},checkActive:{borderColor:'#3157d5',backgroundColor:'#3157d5'},checkText:{color:'#fff',fontWeight:'900'},meta:{flex:1,marginLeft:12},name:{color:'#172033',fontSize:14,fontWeight:'800'},kind:{marginTop:2,color:'#68748a',fontSize:11},empty:{padding:30,alignItems:'center'},emptyTitle:{color:'#172033',fontWeight:'800'},footer:{position:'absolute',left:0,right:0,bottom:0,minHeight:74,paddingHorizontal:14,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:10,borderTopWidth:1,borderTopColor:'#e2e7f0',backgroundColor:'#fff'},selectedCount:{flex:1,color:'#68748a',fontSize:12},forwardButton:{minWidth:110,minHeight:46,paddingHorizontal:20,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:'#3157d5'},forwardText:{color:'#fff',fontWeight:'800'},disabled:{opacity:.55}});
