import React, { useEffect, useMemo, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiClient } from '../services/platform';

export default function PollEditModal({ visible, poll, pollId, onClose, onUpdated }) {
  const [question,setQuestion]=useState(''),[options,setOptions]=useState([]),[expiry,setExpiry]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[calendarOpen,setCalendarOpen]=useState(false),[calendarMonth,setCalendarMonth]=useState(new Date());
  useEffect(()=>{if(!visible)return;setQuestion(poll?.question||'');setOptions((poll?.options||[]).map(o=>({id:o.id,text:o.text||''})));setExpiry(poll?.expires_at?String(poll.expires_at).slice(0,10):'');setError('');setCalendarOpen(false);const d=poll?.expires_at?new Date(String(poll.expires_at).slice(0,10)+'T12:00:00'):new Date();setCalendarMonth(Number.isNaN(d.getTime())?new Date():d)},[visible,poll]);
  const formatDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const days=useMemo(()=>{const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate(),a=[];for(let i=0;i<first;i++)a.push(null);for(let d=1;d<=count;d++)a.push(new Date(y,m,d));return a},[calendarMonth]);
  const normalize=value=>{const s=String(value||'').trim();if(!s||!/^\d{4}-\d{2}-\d{2}$/.test(s))return null;const [y,m,d]=s.split('-').map(Number),v=new Date(y,m-1,d,23,59,59,999);return Number.isNaN(v.getTime())||v.getFullYear()!==y||v.getMonth()!==m-1||v.getDate()!==d?null:v.toISOString()};
  const save=async()=>{const q=question.trim(),o=options.map(x=>({id:Number(x.id)||0,text:String(x.text||'').trim()}));if(!q||o.length<2||o.length>4||o.some(x=>!x.text)||new Set(o.map(x=>x.text)).size!==o.length){setError('Provide a question and 2 to 4 different options.');return}setBusy(true);setError('');try{const expiresAt=normalize(expiry);if(expiry.trim()&&!expiresAt){setError('Choose a valid expiry date.');setBusy(false);return}const {data}=await apiClient.post('v1/polls',{poll_id:pollId,question:q,expires_at:expiresAt,options:o},{query:{action:'edit'}});if(data?.message?.poll)onUpdated?.(data.message);onClose?.()}catch(e){setError(e.message||'Unable to edit poll.')}finally{setBusy(false)}};
  return <Modal visible={visible} transparent animationType="none" onRequestClose={()=>!busy&&onClose?.()}><View style={s.overlay}><View style={s.card}><Text style={s.title}>Edit Poll</Text>{error?<Text style={s.error} accessibilityRole="alert">{error}</Text>:null}<TextInput style={s.input} value={question} onChangeText={setQuestion} placeholder="Poll question" editable={!busy} showSoftInputOnFocus />{options.map((o,i)=><View key={o.id||i} style={s.row}><TextInput style={[s.input,{flex:1}]} value={o.text} onChangeText={v=>setOptions(a=>a.map((x,j)=>j===i?{...x,text:v}:x))} placeholder={`Option ${i+1}`} editable={!busy} showSoftInputOnFocus /><Pressable disabled={busy||options.length<=2} onPress={()=>setOptions(a=>a.filter((_,j)=>j!==i))}><Text style={s.remove}>×</Text></Pressable></View>)}{options.length<4?<Pressable disabled={busy} onPress={()=>setOptions(a=>[...a,{id:0,text:''}])}><Text style={s.add}>+ Add option</Text></Pressable>:null}<Pressable disabled={busy} onPress={()=>{const d=expiry?new Date(expiry+'T12:00:00'):new Date();setCalendarMonth(Number.isNaN(d.getTime())?new Date():d);setCalendarOpen(true)}} style={s.date} accessibilityRole="button" accessibilityLabel="Choose expiry date"><Text style={s.icon}>▣</Text><Text style={s.dateText}>{expiry||'Choose expiry date (optional)'}</Text></Pressable>{calendarOpen?<View style={s.cal}><View style={s.head}><Pressable onPress={()=>setCalendarMonth(d=>new Date(d.getFullYear(),d.getMonth()-1,1))}><Text style={s.nav}>‹</Text></Pressable><Text style={s.calTitle}>{calendarMonth.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</Text><Pressable onPress={()=>setCalendarMonth(d=>new Date(d.getFullYear(),d.getMonth()+1,1))}><Text style={s.nav}>›</Text></Pressable></View><View style={s.week}>{['S','M','T','W','T','F','S'].map((x,i)=><Text key={x+i} style={s.weekDay}>{x}</Text>)}</View><View style={s.grid}>{days.map((d,i)=>{if(!d)return <View key={'b'+i} style={s.day}/>;const today=new Date();today.setHours(0,0,0,0),disabled=d<today,selected=expiry===formatDate(d);return <Pressable key={formatDate(d)} disabled={disabled||busy} onPress={()=>{setExpiry(formatDate(d));setCalendarOpen(false)}} style={[s.day,selected&&s.selected,disabled&&s.disabled]}><Text style={[s.dayText,selected&&s.selectedText,disabled&&s.disabledText]}>{d.getDate()}</Text></Pressable>})}</View></View>:null}<View style={s.actions}><Pressable disabled={busy} onPress={onClose}><Text style={s.cancel}>Cancel</Text></Pressable><Pressable disabled={busy} onPress={save}><Text style={s.save}>{busy?'Saving…':'Save Changes'}</Text></Pressable></View></View></View></Modal>
}
const s=StyleSheet.create({overlay:{flex:1,backgroundColor:'rgba(0,0,0,0.45)',justifyContent:'center',padding:20},card:{borderRadius:16,padding:16,gap:10,maxHeight:'90%',backgroundColor:'#fff'},title:{fontSize:18,fontWeight:'800',color:'#172033'},input:{minHeight:44,borderWidth:1,borderColor:'#d8deea',borderRadius:10,paddingHorizontal:12,color:'#172033',backgroundColor:'#fff'},row:{flexDirection:'row',alignItems:'center',gap:8},remove:{color:'#b91c1c',fontSize:28,paddingHorizontal:4},add:{color:'#3157d5',fontWeight:'800',paddingVertical:4},error:{color:'#b91c1c',fontWeight:'700'},date:{minHeight:44,borderWidth:1,borderColor:'#d8deea',borderRadius:10,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'#fff'},icon:{fontSize:18,color:'#3157d5'},dateText:{color:'#172033',flex:1},cal:{borderWidth:1,borderColor:'#d8deea',borderRadius:12,padding:8,backgroundColor:'#fff'},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},nav:{fontSize:28,color:'#3157d5',paddingHorizontal:8},calTitle:{fontWeight:'800',color:'#172033'},week:{flexDirection:'row'},weekDay:{width:'14.2857%',textAlign:'center',fontSize:11,fontWeight:'800',color:'#68748a',paddingVertical:4},grid:{flexDirection:'row',flexWrap:'wrap'},day:{width:'14.2857%',minHeight:36,alignItems:'center',justifyContent:'center',borderRadius:18},selected:{backgroundColor:'#3157d5'},disabled:{opacity:.35},dayText:{color:'#172033',fontSize:13,fontWeight:'600'},selectedText:{color:'#fff',fontWeight:'800'},disabledText:{color:'#9aa3b2'},actions:{flexDirection:'row',justifyContent:'flex-end',gap:18,paddingTop:8},cancel:{color:'#64748b',fontWeight:'800'},save:{color:'#3157d5',fontWeight:'800'}});
