import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { platformApi } from '../services/platform';
import { resolveChatTheme } from '../services/chatThemeDefinitions';
const REASONS = ['Harassment', 'Spam', 'Hate or abusive content', 'Impersonation', 'Unsafe content', 'Other'];
export default function PublicChatManagement({ visible, chat, user, onClose, onLeave, themeSettings }) {
 const theme=resolveChatTheme(themeSettings);
 const [screen,setScreen]=useState('menu'),[users,setUsers]=useState([]),[participants,setParticipants]=useState([]),[selectedUser,setSelectedUser]=useState(null),[reason,setReason]=useState(REASONS[0]),[details,setDetails]=useState(''),[loading,setLoading]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!visible){setScreen('menu');setSelectedUser(null);setDetails('');setError('');return undefined;}let active=true;const load=async()=>{setLoading(true);try{const {data}=await platformApi.getPublicChatManage(chat.id);if(active){setUsers(data.online_users||[]);setParticipants(data.participants||[]);}}catch(e){if(active)setError(e.message||'Unable to load room members.');}finally{if(active)setLoading(false);}};load();const timer=setInterval(load,10000);return()=>{active=false;clearInterval(timer);};},[visible,chat?.id]);
 const report=async()=>{if(!selectedUser||Number(selectedUser.id)===Number(user.id)||submitting)return;setSubmitting(true);setError('');try{await platformApi.reportPublicChatUser(chat.id,{reported_user_id:Number(selectedUser.id),reason,details:details.trim(),incident_key:'incident-'+Date.now()+'-'+Math.random().toString(36).slice(2,12)});Alert.alert('Report submitted','Your report was securely recorded for moderator review.');setSelectedUser(null);setDetails('');}catch(e){setError(e.message||'Unable to submit report.');}finally{setSubmitting(false);}};
 const confirmLeave=()=>Alert.alert('Leave this room?','You will leave this public chat room and can join again unless a moderation restriction prevents access.',[{text:'Cancel',style:'cancel'},{text:'Leave Room',style:'destructive',onPress:onLeave}]);
 const title=screen==='menu'?'Manage Public Chat':screen==='users'?'Online Users':'Report User';
 return <Modal visible={visible} transparent animationType='slide' onRequestClose={onClose}><View style={styles.overlay}><View style={[styles.card,{backgroundColor:theme.colors.background}]}><View style={styles.header}><Text style={[styles.title,{color:theme.colors.text}]}>{title}</Text><Pressable onPress={onClose}><Text style={[styles.close,{color:theme.colors.secondary}]}>×</Text></Pressable></View>
 {screen==='menu'?<View style={styles.menu}><Pressable style={[styles.menuItem,{borderColor:theme.colors.border,backgroundColor:theme.colors.background}]} onPress={()=>setScreen('users')}><Text style={[styles.menuTitle,{color:theme.colors.text}]}>Online Users</Text><Text style={[styles.menuText,{color:theme.colors.secondary}]}>See users currently online in this room.</Text></Pressable><Pressable style={[styles.menuItem,{borderColor:theme.colors.border,backgroundColor:theme.colors.background}]} onPress={()=>setScreen('report')}><Text style={[styles.menuTitle,{color:theme.colors.text}]}>Report User</Text><Text style={[styles.menuText,{color:theme.colors.secondary}]}>Report a participant for moderator review.</Text></Pressable><Pressable style={[styles.menuItem,styles.leaveItem]} onPress={confirmLeave}><Text style={styles.leaveText}>Leave Chat / Leave Room</Text></Pressable></View>:<><Pressable onPress={()=>{setScreen('menu');setSelectedUser(null);}}><Text style={[styles.back,{color:theme.colors.accent}]}>‹ Manage</Text></Pressable>{loading?<View style={styles.loading}><ActivityIndicator color={theme.colors.accent}/><Text>Loading…</Text></View>:null}{error?<View style={styles.errorBox}><Text style={styles.error}>{error}</Text></View>:null}
 {screen==='users'?<ScrollView style={styles.list}>{users.length?users.map(item=><View key={item.id} style={[styles.userRow,{borderBottomColor:theme.colors.border}]}><View style={styles.dot}/><View style={styles.userMeta}><Text style={[styles.userName,{color:theme.colors.text}]}>{item.name||'Member'}</Text><Text style={[styles.userSub,{color:theme.colors.secondary}]}>Online now</Text></View></View>):<Text style={[styles.empty,{color:theme.colors.secondary}]}>No users are currently online.</Text>}</ScrollView>:<ScrollView style={styles.list}>{participants.filter(item=>Number(item.id)!==Number(user.id)).map(item=><Pressable key={item.id} style={[styles.userRow,{borderBottomColor:theme.colors.border}]} onPress={()=>setSelectedUser(item)}><View style={[styles.dot,!item.online&&styles.offline]}/><View style={styles.userMeta}><Text style={[styles.userName,{color:theme.colors.text}]}>{item.name||'Member'}</Text><Text style={[styles.userSub,{color:theme.colors.secondary}]}>{item.online?'Online now':'Participant'}</Text></View></Pressable>)}<Text style={[styles.sectionLabel,{color:theme.colors.text}]}>Reason</Text><View style={styles.reasonWrap}>{REASONS.map(item=><Pressable key={item} style={[styles.reason,reason===item&&styles.reasonActive]} onPress={()=>setReason(item)}><Text style={[styles.reasonText,reason===item&&styles.reasonTextActive]}>{item}</Text></Pressable>)}</View><TextInput style={[styles.details,{color:theme.colors.text,borderColor:theme.colors.border,backgroundColor:theme.colors.background}]} value={details} onChangeText={setDetails} maxLength={2000} multiline placeholder='Additional details (optional)' placeholderTextColor='#7f8aa3'/><Pressable style={[styles.submit,(!selectedUser||submitting)&&styles.disabled]} disabled={!selectedUser||submitting} onPress={report}><Text style={styles.submitText}>{submitting?'Submitting…':'Submit Report'}</Text></Pressable></ScrollView>}</>}</View></View></Modal>;
}
const styles=StyleSheet.create({overlay:{flex:1,backgroundColor:'#0008',justifyContent:'flex-end'},card:{maxHeight:'86%',backgroundColor:'#fff',borderTopLeftRadius:22,borderTopRightRadius:22,padding:18},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12},title:{fontSize:19,fontWeight:'800',color:'#172033'},close:{fontSize:30,color:'#68748a'},back:{color:'#3157d5',fontWeight:'800',marginBottom:10},menu:{gap:10},menuItem:{padding:15,borderWidth:1,borderColor:'#e1e6ef',borderRadius:14},menuTitle:{fontSize:14,fontWeight:'800',color:'#172033'},menuText:{marginTop:4,fontSize:11,color:'#68748a'},leaveItem:{marginTop:6,borderColor:'#fecaca'},leaveText:{fontSize:14,fontWeight:'800',color:'#b91c1c'},list:{maxHeight:520},loading:{padding:12,alignItems:'center',gap:6},errorBox:{padding:10,backgroundColor:'#fff1f2',borderRadius:10},error:{color:'#b91c1c'},userRow:{flexDirection:'row',alignItems:'center',paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#edf0f5'},dot:{width:9,height:9,borderRadius:5,backgroundColor:'#16a34a',marginHorizontal:8},offline:{backgroundColor:'#cbd5e1'},userMeta:{flex:1},userName:{fontSize:14,fontWeight:'700',color:'#172033'},userSub:{marginTop:2,fontSize:10,color:'#68748a'},empty:{padding:25,textAlign:'center',color:'#68748a'},sectionLabel:{marginTop:12,marginBottom:7,fontSize:12,fontWeight:'800',color:'#172033'},reasonWrap:{flexDirection:'row',flexWrap:'wrap',gap:7},reason:{paddingVertical:8,paddingHorizontal:10,borderRadius:16,borderWidth:1,borderColor:'#d5dceb'},reasonActive:{borderColor:'#3157d5',backgroundColor:'#eef2ff'},reasonText:{fontSize:11,color:'#4b5563'},reasonTextActive:{color:'#3157d5',fontWeight:'800'},details:{minHeight:90,borderWidth:1,borderColor:'#d5dceb',borderRadius:12,padding:10,marginTop:12,color:'#172033',textAlignVertical:'top'},submit:{marginTop:12,padding:13,borderRadius:12,backgroundColor:'#3157d5',alignItems:'center'},disabled:{opacity:.5},submitText:{color:'#fff',fontWeight:'800'}});