import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
export const documents = [
  ['privacy', 'Privacy Policy', 'privacy-policy'],
  ['terms', 'Terms & Conditions', 'terms-of-service'],
  ['deletion', 'Account & data deletion', 'account-deletion'],
];
const escapeHtml = value => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
function inline(text) {
  return text.split(/(https:\/\/[^\s]+|support@cloudcomai\.com)/g).map(part => {
    if (part === 'support@cloudcomai.com') return `<a href="mailto:${part}">${part}</a>`;
    if (part.startsWith('https://')) return `<a href="${escapeHtml(part)}" rel="noreferrer">${escapeHtml(part)}</a>`;
    return escapeHtml(part);
  }).join('');
}
export function renderLegalHtml(title, source) {
  const blocks = source.trim().split(/\n\s*\n/).slice(1).map(block => {
    if (/^\d+\. [^\n]+$/.test(block)) return `<h2>${inline(block)}</h2>`;
    const lines = block.split('\n');
    if (lines.every(line => line.startsWith('* '))) return `<ul>${lines.map(line => `<li>${inline(line.slice(2))}</li>`).join('')}</ul>`;
    return `<p>${lines.map(inline).join('<br>')}</p>`;
  }).join('\n');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="referrer" content="no-referrer"><title>CloudComAI — ${escapeHtml(title)}</title>
<style>body{margin:0;background:#f5f7fb;color:#172033;font:17px/1.65 system-ui,sans-serif}main{max-width:850px;margin:auto;padding:32px 22px 64px;background:#fff}nav{display:flex;flex-wrap:wrap;gap:12px 24px;border-bottom:1px solid #d8deea;padding-bottom:20px}a{color:#2446ac;overflow-wrap:anywhere}h1{font-size:2rem;line-height:1.2}h2{font-size:1.25rem;margin-top:32px}p,li{overflow-wrap:anywhere}a:focus-visible{outline:3px solid #eaa400;outline-offset:3px}@media print{body{background:#fff}nav{display:none}}</style></head>
<body><main><nav aria-label="Legal documents">${documents.map(([, label, name]) => `<a href="./${name}.html">${escapeHtml(label)}</a>`).join('')}<a href="./">CloudComAI home</a></nav><h1>CloudComAI ${escapeHtml(title)}</h1>${blocks}</main></body></html>
`;
}
export async function buildLegalArtifacts({ check = false } = {}) {
  const contentRoot = path.join(root, 'apps/web/src/content');
  const legalDocuments = {};
  const outputs = [];
  for (const [id, title, name] of documents) {
    const text = await readFile(path.join(contentRoot, `${name}.txt`), 'utf8');
    legalDocuments[id] = { title, text };
    outputs.push([path.join(root, `apps/web/public/${name}.html`), renderLegalHtml(title, text)]);
  }
  const registrationNotice = await readFile(path.join(contentRoot, 'registration-notice.txt'), 'utf8');
  outputs.push([path.join(root, 'apps/mobile/src/content/legalDocuments.js'), `// Generated by scripts/generate-legal.mjs. Edit apps/web/src/content/*.txt instead.\nexport const legalDocuments = ${JSON.stringify(legalDocuments, null, 2)};\nexport const registrationNotice = ${JSON.stringify(registrationNotice.trim())};\n`]);
  for (const [file, content] of outputs) {
    if (check) {
      if (await readFile(file, 'utf8').catch(() => '') !== content) throw new Error(`Legal artifact is stale: ${path.relative(root, file)}. Run pnpm legal:generate.`);
    } else {
      await mkdir(path.dirname(file), { recursive: true });
      await writeFile(file, content);
    }
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  await buildLegalArtifacts({ check: process.argv.includes('--check') });
}
