export const ApiRoute = Object.freeze({
  LOGIN: 'v1/auth/login',
  REGISTER: 'v1/auth/register',
  FORGOT_PASSWORD: 'v1/auth/forgot-password',
  RESET_PASSWORD: 'v1/auth/reset-password',
  PROFILE: 'v1/users/me',
  USERS: 'v1/users',
  SEARCH_USERS: 'v1/users/search',
  CHATS: 'v1/chats',
  GROUPS: 'v1/groups',
  GROUP_MEMBERS: 'v1/group-members',
  MESSAGES: 'v1/messages',
  EDIT_MESSAGE: 'v1/messages/edit',
  POLLS: 'v1/polls',
  UPLOAD_ATTACHMENT: 'v1/attachments/upload',
  ATTACHMENT: 'v1/attachments',
  ATTACHMENT_REQUESTS: 'v1/attachment-requests',
  REQUEST_ATTACHMENT_DOWNLOAD: 'v1/attachment-requests/request',
  RESPOND_ATTACHMENT_DOWNLOAD: 'v1/attachment-requests/respond',
  CONTACTS: 'v1/contacts',
  GOOGLE_CONNECT: 'v1/integrations/google/connect',
  GOOGLE_STATUS: 'v1/integrations/google/status',
  GOOGLE_SYNC: 'v1/integrations/google/sync',
  GOOGLE_CONTACTS: 'v1/integrations/google/contacts',
  HEARTBEAT: 'v1/presence/heartbeat',
  HEALTH: 'v1/health',
  CALLS: 'v1/calls',
  LIVE_LOCATION: 'v1/live-locations',
  STORIES: 'v1/stories',
  MEDIA: 'v1/media',
  MEDIA_UPLOAD: 'v1/media/upload',
  JOIN: 'v1/invitations/join',
});

// Backward-compatible alias for Phase 2 consumers. New code should use ApiRoute.
export const ApiEndpoint = ApiRoute;
