import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const media = fs.readFileSync(new URL('../src/components/MediaMessage.js', import.meta.url), 'utf8');
const pollEditor = fs.readFileSync(new URL('../src/components/PollEditModal.js', import.meta.url), 'utf8');
const app = fs.readFileSync(new URL('../App.js', import.meta.url), 'utf8');
const composer = fs.readFileSync(new URL('../src/components/MediaComposer.js', import.meta.url), 'utf8');
const mobileMenu = fs.readFileSync(new URL('../src/components/MobileMenu.js', import.meta.url), 'utf8');

test('mobile poll editing exposes creator-only edit flow with two-edit eligibility', () => {
  assert.match(media, /message\.type === 'poll'/);
  assert.match(pollEditor, /query:\{action:'edit'\}/);
  assert.match(pollEditor, /Edit Poll/);
  assert.doesNotMatch(media, /pollEditOpen/);
  assert.match(pollEditor, /animationType="none"/);
  assert.match(pollEditor, /showSoftInputOnFocus/);
  assert.match(app, /Keyboard\.addListener\('keyboardDidShow'/);
  assert.match(app, /PollEditModal/);
  assert.match(app, /onEditPoll/);
  assert.match(app, /if \(keyboardVisibleRef\.current\) return/);
  assert.match(pollEditor, /2 to 4 different options/);
  assert.match(pollEditor, /const normalize/);
  assert.match(pollEditor, /!\/\^\\d\{4\}-\\d\{2\}-\\d\{2\}\$\/\.test\(s\)/);
  assert.match(pollEditor, /Choose a valid expiry date\./);
  assert.match(pollEditor, /expiresAt\s*=\s*normalize\(expiry\)/);
  assert.match(pollEditor, /Choose expiry date/);
  assert.match(pollEditor, /calendarOpen/);
  assert.match(pollEditor, /const days/);
  assert.match(pollEditor, /grid:\{flexDirection:'row',flexWrap:'wrap'\}/);
  assert.match(pollEditor, /accessibilityRole="alert"/);
  assert.match(pollEditor, /accessibilityRole="alert"/);
  assert.match(media, /colors\.iconPrimary \|\| colors\.accent \|\| '#1677c8'/);
  assert.match(media, /function MessageAction\(\{ type, label, color, onPress, accessibilityLabel, colors = \{\} \}\)/);
  assert.match(media, /colors\.surfaceSecondary \|\| colors\.primaryLight/);
  assert.match(media, /colors\.surface \|\| colors\.composer/);
  assert.match(media, /pressed && \{ backgroundColor: pressedBackground \}/);
  assert.match(app, /const canEditPoll = message =>/);
  assert.match(app, /message\?\.type !== 'poll'/);
  assert.match(app, /Number\(message\?\.edit_count \|\| 0\) >= 2/);
  assert.match(app, /const openPollComposer = \(\) =>/);
  assert.match(app, /visible=\{pollMenuVisible\}/);
  assert.match(app, /initialScreen="poll"/);
  assert.match(composer, /chat\.isGroup && onCreatePoll/);
  assert.match(mobileMenu, /const \[pollCalendarOpen, setPollCalendarOpen\] = useState\(false\)/);
  assert.match(mobileMenu, /pollCalendarGrid: \{ flexDirection: 'row', flexWrap: 'wrap' \}/);
  assert.match(mobileMenu, /Choose expiry date/);
  assert.match(mobileMenu, /selectPollExpiryDate/);
  assert.match(app, /<MediaComposer chat=\{chat\} onMessage=\{onMediaMessage\} onCreatePoll=\{openPollComposer\} \/>/);
  assert.match(app, /initialPollChatId=\{chat\.id\}/);
  assert.match(composer, /onCreatePoll/);
  assert.match(mobileMenu, /initialPollChatId = null/);
  assert.match(mobileMenu, /loadPollConversations\(initialPollChatId\)/);
  assert.match(mobileMenu, /const preferred = chats\.find\(chat => Number\(chat\.id\) === Number\(preferredChatId\)\)/);
  assert.match(mobileMenu, /Poll question is required\./);
  assert.match(mobileMenu, /Provide at least 2 options\./);
  assert.match(mobileMenu, /A poll can have at most 4 options\./);
  assert.match(mobileMenu, /pollValidationError/);
  assert.match(mobileMenu, /error && screen !== 'poll'/);
  assert.match(mobileMenu, /accessibilityRole="alert"/);
  assert.match(composer, /<Text style=\{styles\.link\}>Poll<\/Text>/);
});
