name: Temporary lockfile generation
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --lockfile-only
      - uses: actions/upload-artifact@v4
        with:
          name: generated-pnpm-lock
          path: pnpm-lock.yaml
